[package]
name = "memtrack-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.164"
ctor = "0.4.2"
process_path = "0.1.4"
mach2 = "0.4.2"
fishhook = "0.1.1"

[dependencies.utils]
version = "0.1.0"
path = "utils"

[lib]
path = "src/lib.rs"
crate-type = ["dylib"]