[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
byteorder = "1.5.0"
thiserror = "2.0"
indexmap = "2.7.0"
