[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
byteorder = "1.5.0"
